services:
  
  visualization-app:
    env_file:
      - dev.env
    image: pennsieve/visualization-app
    volumes:
      - ./data:/service/data
    container_name: visualization-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8050:8050"
